export const details = (data) => [
    { label: 'تاریخ ایجاد', value: data?.['Creation Date'] },
    { label: 'نام فارسی', value: data?.['Persian Name'] },
    { label: 'نام فارسی پیشنهادی', value: data?.['Persian Suggested Symbol'] },
    { label: 'نماد تایید شده', value: data?.['Persian Approved Symbol'] },
    { label: 'نام انگلیسی', value: data?.['English Name'] },
    { label: 'نام انگلیسی پیشنهادی', value: data?.['English Suggested Symbol'] },
    { label: 'نماد انگلیسی تایید شده', value: data?.['English Approved Symbol'] },
    { label: 'کد گروه صنعت', value: data?.['Industry Group ID'] },
    { label: 'عنوان گروه صنعت', value: data?.['Industry Group Description'] },
    { label: 'عنوان زیر گروه صنعت', value: data?.['Sub Industry Group Description'] },
    { label: 'شرح فارسی', value: data?.['Persian Subject'] },
    { label: 'شرح انگلیسی', value: data?.['English Subject'] },
    { label: 'قیمت اسمی هر گواهی شراکت (ریال)', value: data?.['Unit Price'] },
    { label: 'تعداد کل گواهی های شراکت قابل عرضه', value: data?.['Total Units'] },
    { label: 'تعداد گواهی شراکت متقاضی', value: data?.['Company Unit Counts'] },
    { label: 'مبلغ مورد نیاز (ریال)', value: data?.['Total Price'] },
    { label: 'کد نوع تامین مالی', value: data?.['Crowd Funding Type ID'] },
    { label: 'عنوان نوع تامین مالی', value: data?.['Crowd Funding Type Description'] },
    { label: 'دلیل شناور بودن', value: data?.['Float Crowd Funding Type Description'] },
    { label: 'حداقل مبلغ مورد نیاز جهت موفقیت تامین مالی (ریال)', value: data?.['Minimum Required Price'] },
    { label: 'حداقل مبلغ سرمایه گذاری برای تامین کننده حقیقی (ریال)', value: data?.['Real Person Minimum Availabe Price'] },
    { label: 'حداکثر مبلغ سرمایه گذاری برای تامین کننده حقیقی (ریال)', value: data?.['Real Person Maximum Available Price'] },
    { label: 'حداقل مبلغ سرمایه گذاری برای تامین کننده حقوقی (ریال)', value: data?.['Legal Person Minimum Available Price'] },
    { label: 'حداکثر مبلغ سرمایه گذاری برای تامین کننده حقوقی (ریال)', value: data?.['Legal Person Maximum Available Price'] },
    { label: 'تاریخ شروع جمع آوری وجوه', value: data?.['Underwriting start Date'] },
    { label: 'تاریخ پایان جمع آوری وجوه', value: data?.['Underwriting End Date'] },
    { label: 'تاریخ شروع اجرای طرح', value: data?.['Project Start Date'] },
    { label: 'تاریخ پایان اجرای طرح', value: data?.['Project End Date'] },
    { label: 'زمانبندی ارائه گزارش', value: data?.['Project Reporting Type Description'] },
    { label: 'نحوه تسویه', value: data?.['Settlement Description'] },
    { label: 'وضعیت پروژه', value: data?.['Project Status Description'] },
    { label: 'کد وضعیت پروژه', value: data?.['Project Status ID'] },
    { label: 'تعداد مشارکت کنندگان در تامین مالی پروژه', value: data?.['Number Of Finance Provider'] },
    { label: 'مبلغ جمع آوری شده در تامین مالی پروژه', value: data?.['Sum Of Funding Provider'] },
    { label: 'اطلاعات ثبتی شرکت متقاضی', value: data?.['Project Owner Company'] },
    { label: 'اطلاعات سهامداران بالای 10 درصد', value: data?.['List Of Project Big Share Holders'] },
    { label: 'اطلاعات مدیرعامل و اعضای هیئت مدیره', value: data?.['List Of Project Board Members'] },
  ];
  